logging:
  config: classpath:logback.xml
  path: d:/logs
server:
  port: 8081
  session-timeout: 60

mybatis:
     mapperLocations: classpath:mapper/*.xml
     typeAliasesPackage: com.fei.springboot.dao
     mapperScanPackage: com.fei.springboot.dao
     configLocation: classpath:/mybatis-config.xml

spring:
    datasource:
        name: db
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/o2o?useUnicode=true&amp;characterEncoding=utf-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        minIdle: 5
        maxActive: 100
        initialSize: 10
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 50
        removeAbandoned: true
        filters: stat
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true
        druidLoginName: wjf
        druidPassword: wjf
        cachePrepStmts: true
    redis:
        database:  0
        host:  127.0.0.1
        port:  6379
        password: root
        jedis:
          pool:
            max-active: 8
            max-idle: 8
            max-wait:
            min-idle: 0
        timeout: 100000